### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8Jupyter#1]
broken links in 
https://github.com/SpiNNakerManchester/sPyNNaker8Jupyter/blob/master/sPyNNakerNRPJupyter/03.NeuroroboticsPlatform/%20NeuroroboticsPlatform.ipynb

**Comment by Christian-B** [comment]
http://schemas.humanbrainproject.eu does not appear to work (nor https)

**Comment by dkfellows** [comment]
~Is the link `https://spinn-20.cs.man.ac.uk/user/<username>/proxy/9000/#/esv-private`? That's obviously and intentionally broken...~

Oh, I see. XML Schema. Those aren't necessarily available at their URL, and XML schemas have _always_ been rather like that.

**Comment by rowleya** [comment]
The file is meant to be used on the Jupyter service.  The URLs contained within the bibi file are NRP-controlled.  I don't know if they ever existed, or if they are just used for the schema...

**Comment by Christian-B** [comment]
Closing as this is likely an unpublished or published else where URL
